[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
# pyo3 = { version = "0.26.0", features = ["auto-initialize"] }
rustpython-parser = "0.4.0"

[dev-dependencies]
rstest = "0.26.1"
